const actions = {
    COLLAPSE_MENU: 'COLLAPSE_MENU',
    COLLAPSE_TOGGLE: 'COLLAPSE_TOGGLE',
    FULL_SCREEN: 'FULL_SCREEN',
    FULL_SCREEN_EXIT: 'FULL_SCREEN_EXIT',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    NAV_CONTENT_LEAVE: 'NAV_CONTENT_LEAVE',
    NAV_COLLAPSE_LEAVE: 'NAV_COLLAPSE_LEAVE',
    GET_ALL_USER_LIST_SUCCES: "GET_ALL_USER_LIST_SUCCES",

    CHANGE_USER: "CHANGE_USER",
    CURRENT_USER: "CURRENT_USER",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT: "LOGOUT",
}
export default actions;
